# -*- coding: utf-8 -*-
"""area_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsNwC4tsD-Z-ZCgi7MKgF17MVy_MUiE7
"""

# Write the content of area_calculator.py here in a string format

area_calculator_code = '''
import streamlit as st
import math

def show_area():
    st.header("Area Calculator")
    shape = st.selectbox("Choose a shape", ["Circle", "Rectangle", "Triangle"])

    if shape == "Circle":
        radius = st.number_input("Radius (units)", value=1.0)
        if st.button("Calculate Area (Circle)"):
            area = math.pi * radius ** 2
            st.success(f"Area of circle = {area:.2f} square units")

    elif shape == "Rectangle":
        length = st.number_input("Length (units)", value=2.0)
        width = st.number_input("Width (units)", value=1.0)
        if st.button("Calculate Area (Rectangle)"):
            area = length * width
            st.success(f"Area of rectangle = {area:.2f} square units")

    elif shape == "Triangle":
        base = st.number_input("Base (units)", value=2.0)
        height = st.number_input("Height (units)", value=1.0)
        if st.button("Calculate Area (Triangle)"):
            area = 0.5 * base * height
            st.success(f"Area of triangle = {area:.2f} square units")
'''

with open("area_calculator.py", "w") as file:
    file.write(area_calculator_code)