# -*- coding: utf-8 -*-
"""bmi_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mNvr2MEeGc_fSqvFMk3tCWH7RqeyT1J
"""

# Write the content of bmi_calculator.py here in a string format

bmi_calculator_code = '''
import streamlit as st

def interpret_bmi(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 25:
        return "Normal weight"
    elif 25 <= bmi < 30:
        return "Overweight"
    else:
        return "Obesity"

def show_bmi():
    st.header("BMI Calculator")
    weight = st.number_input("Weight (kg)", min_value=0.0, value=70.0)
    height = st.number_input("Height (m)", min_value=0.0, value=1.70)

    if st.button("Calculate BMI"):
        if height <= 0:
            st.error("Height must be greater than 0")
        else:
            bmi = weight / (height ** 2)
            category = interpret_bmi(bmi)
            st.success(f"BMI: {bmi:.2f}")
            st.info(f"Category: {category}")
'''

with open("bmi_calculator.py", "w") as file:
    file.write(bmi_calculator_code)