# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ya3mVSxTepz1Tpw5c4cUfXxfMsXSVZH9
"""

# Write the content of calculator.py here in a string format

calculator_code = '''
import streamlit as st
import math

def show_calculator():
    st.header("Calculator App")
    st.write("Do numbers daalein, operation choose karein, phir Calculate press karein.")
    num1 = st.number_input("First number", value=0.0, format="%.8f")
    num2 = st.number_input("Second number", value=0.0, format="%.8f")
    operation = st.selectbox("Choose operation", ["+", "-", "*", "/", "Simple Interest (SI)", "Compound Interest (CI)", "Square", "Square Root"])
    principal, rate, time, freq = None, None, None, None

    if operation in ("Simple Interest (SI)", "Compound Interest (CI)"):
        principal = st.number_input("Principal (P)", value=num1 if num1 != 0 else 100.0)
        rate = st.number_input("Annual Rate (%)", value=5.0)
        time = st.number_input("Time (years)", value=1.0)
        if operation == "Compound Interest (CI)":
            freq = st.selectbox("Compounding frequency", [1, 2, 4, 12])

    if st.button("Calculate"):
        if operation == "+":
            result = num1 + num2
        elif operation == "-":
            result = num1 - num2
        elif operation == "*":
            result = num1 * num2
        elif operation == "/":
            if num2 != 0:
                result = num1 / num2
            else:
                st.error("Division by zero!")
                result = None
        elif operation == "Square":
            result = num1 ** 2
        elif operation == "Square Root":
            result = math.sqrt(num1)
        elif operation == "Simple Interest (SI)":
            result = (principal * rate * time) / 100
        elif operation == "Compound Interest (CI)":
            A = principal * (1 + rate / 100 / freq) ** (freq * time)
            result = A - principal

        if result:
            st.success(f"Result: {result}")
'''

with open("calculator.py", "w") as file:
    file.write(calculator_code)